/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Direction = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
export const EventType = IDL.Variant({
  'laneDeparture' : IDL.Record({ 'direction' : Direction }),
  'speedViolation' : IDL.Record({ 'speed' : IDL.Nat }),
  'hardBraking' : IDL.Record({ 'gForce' : IDL.Float64 }),
});
export const Driver = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'birthdate' : IDL.Int,
  'name' : IDL.Text,
  'sessions' : IDL.Vec(IDL.Nat),
  'address' : IDL.Text,
  'licenseNumber' : IDL.Text,
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Nat,
  'eventType' : EventType,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : SessionStatus,
  'driverId' : IDL.Nat,
  'endTime' : IDL.Opt(IDL.Int),
  'events' : IDL.Vec(Event),
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([IDL.Nat, EventType, IDL.Text], [IDL.Nat], []),
  'completeSession' : IDL.Func([IDL.Nat], [], []),
  'createSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getDriver' : IDL.Func([IDL.Nat], [Driver], ['query']),
  'getEventsForSession' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'getSessionsForDriver' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
  'getTotalEventsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isDriverRegistered' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'loginDriver' : IDL.Func([IDL.Nat], [Driver], ['query']),
  'registerDriver' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'seedDemoData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Direction = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
  const EventType = IDL.Variant({
    'laneDeparture' : IDL.Record({ 'direction' : Direction }),
    'speedViolation' : IDL.Record({ 'speed' : IDL.Nat }),
    'hardBraking' : IDL.Record({ 'gForce' : IDL.Float64 }),
  });
  const Driver = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'birthdate' : IDL.Int,
    'name' : IDL.Text,
    'sessions' : IDL.Vec(IDL.Nat),
    'address' : IDL.Text,
    'licenseNumber' : IDL.Text,
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Nat,
    'eventType' : EventType,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : SessionStatus,
    'driverId' : IDL.Nat,
    'endTime' : IDL.Opt(IDL.Int),
    'events' : IDL.Vec(Event),
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([IDL.Nat, EventType, IDL.Text], [IDL.Nat], []),
    'completeSession' : IDL.Func([IDL.Nat], [], []),
    'createSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getDriver' : IDL.Func([IDL.Nat], [Driver], ['query']),
    'getEventsForSession' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'getSessionsForDriver' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
    'getTotalEventsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isDriverRegistered' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'loginDriver' : IDL.Func([IDL.Nat], [Driver], ['query']),
    'registerDriver' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'seedDemoData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };