/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Direction = { 'left' : null } |
  { 'right' : null };
export interface Driver {
  'id' : bigint,
  'principal' : Principal,
  'birthdate' : bigint,
  'name' : string,
  'sessions' : Array<bigint>,
  'address' : string,
  'licenseNumber' : string,
}
export interface Event {
  'id' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'sessionId' : bigint,
  'eventType' : EventType,
}
export type EventType = { 'laneDeparture' : { 'direction' : Direction } } |
  { 'speedViolation' : { 'speed' : bigint } } |
  { 'hardBraking' : { 'gForce' : number } };
export interface Session {
  'id' : bigint,
  'startTime' : bigint,
  'status' : SessionStatus,
  'driverId' : bigint,
  'endTime' : [] | [bigint],
  'events' : Array<Event>,
}
export type SessionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface _SERVICE {
  'addEvent' : ActorMethod<[bigint, EventType, string], bigint>,
  'completeSession' : ActorMethod<[bigint], undefined>,
  'createSession' : ActorMethod<[bigint], bigint>,
  'getAllDrivers' : ActorMethod<[], Array<Driver>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getDriver' : ActorMethod<[bigint], Driver>,
  'getEventsForSession' : ActorMethod<[bigint], Array<Event>>,
  /**
   * / Retrieves summary for a session (does not include data for all events)
   */
  'getSession' : ActorMethod<[bigint], Session>,
  'getSessionsForDriver' : ActorMethod<[bigint], Array<Session>>,
  'getTotalEventsCount' : ActorMethod<[], bigint>,
  'isDriverRegistered' : ActorMethod<[bigint], boolean>,
  'loginDriver' : ActorMethod<[bigint], Driver>,
  'registerDriver' : ActorMethod<[string, string, string, bigint], bigint>,
  'seedDemoData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];