/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Event {
    id: bigint;
    description: string;
    timestamp: bigint;
    sessionId: bigint;
    eventType: EventType;
}
export type EventType = {
    __kind__: "laneDeparture";
    laneDeparture: {
        direction: Direction;
    };
} | {
    __kind__: "speedViolation";
    speedViolation: {
        speed: bigint;
    };
} | {
    __kind__: "hardBraking";
    hardBraking: {
        gForce: number;
    };
};
export interface Session {
    id: bigint;
    startTime: bigint;
    status: SessionStatus;
    driverId: bigint;
    endTime?: bigint;
    events: Array<Event>;
}
export interface Driver {
    id: bigint;
    principal: Principal;
    birthdate: bigint;
    name: string;
    sessions: Array<bigint>;
    address: string;
    licenseNumber: string;
}
export enum Direction {
    left = "left",
    right = "right"
}
export enum SessionStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export interface backendInterface {
    addEvent(sessionId: bigint, eventType: EventType, description: string): Promise<bigint>;
    completeSession(sessionId: bigint): Promise<void>;
    createSession(driverId: bigint): Promise<bigint>;
    getAllDrivers(): Promise<Array<Driver>>;
    getAllSessions(): Promise<Array<Session>>;
    getDriver(driverId: bigint): Promise<Driver>;
    getEventsForSession(sessionId: bigint): Promise<Array<Event>>;
    /**
     * / Retrieves summary for a session (does not include data for all events)
     */
    getSession(sessionId: bigint): Promise<Session>;
    getSessionsForDriver(driverId: bigint): Promise<Array<Session>>;
    getTotalEventsCount(): Promise<bigint>;
    isDriverRegistered(driverId: bigint): Promise<boolean>;
    loginDriver(driverId: bigint): Promise<Driver>;
    registerDriver(name: string, address: string, licenseNumber: string, birthdate: bigint): Promise<bigint>;
    seedDemoData(): Promise<void>;
}
import type { Direction as _Direction, Event as _Event, EventType as _EventType, Session as _Session, SessionStatus as _SessionStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEvent(arg0: bigint, arg1: EventType, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async completeSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSession(arg0);
            return result;
        }
    }
    async createSession(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async getAllDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrivers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrivers();
            return result;
        }
    }
    async getAllSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriver(arg0: bigint): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return result;
        }
    }
    async getEventsForSession(arg0: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsForSession(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsForSession(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: bigint): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_Session_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_Session_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionsForDriver(arg0: bigint): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionsForDriver(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionsForDriver(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalEventsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalEventsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalEventsCount();
            return result;
        }
    }
    async isDriverRegistered(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDriverRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDriverRegistered(arg0);
            return result;
        }
    }
    async loginDriver(arg0: bigint): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.loginDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginDriver(arg0);
            return result;
        }
    }
    async registerDriver(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDriver(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDriver(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
}
function from_candid_Direction_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    timestamp: bigint;
    sessionId: bigint;
    eventType: _EventType;
}): {
    id: bigint;
    description: string;
    timestamp: bigint;
    sessionId: bigint;
    eventType: EventType;
} {
    return {
        id: value.id,
        description: value.description,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        eventType: from_candid_EventType_n15(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
}): {
    direction: Direction;
} {
    return {
        direction: from_candid_Direction_n18(_uploadFile, _downloadFile, value.direction)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _SessionStatus;
    driverId: bigint;
    endTime: [] | [bigint];
    events: Array<_Event>;
}): {
    id: bigint;
    startTime: bigint;
    status: SessionStatus;
    driverId: bigint;
    endTime?: bigint;
    events: Array<Event>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_SessionStatus_n9(_uploadFile, _downloadFile, value.status),
        driverId: value.driverId,
        endTime: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.endTime)),
        events: from_candid_vec_n12(_uploadFile, _downloadFile, value.events)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "cancelled" in value ? SessionStatus.cancelled : "completed" in value ? SessionStatus.completed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    laneDeparture: {
        direction: _Direction;
    };
} | {
    speedViolation: {
        speed: bigint;
    };
} | {
    hardBraking: {
        gForce: number;
    };
}): {
    __kind__: "laneDeparture";
    laneDeparture: {
        direction: Direction;
    };
} | {
    __kind__: "speedViolation";
    speedViolation: {
        speed: bigint;
    };
} | {
    __kind__: "hardBraking";
    hardBraking: {
        gForce: number;
    };
} {
    return "laneDeparture" in value ? {
        __kind__: "laneDeparture",
        laneDeparture: from_candid_record_n17(_uploadFile, _downloadFile, value.laneDeparture)
    } : "speedViolation" in value ? {
        __kind__: "speedViolation",
        speedViolation: value.speedViolation
    } : "hardBraking" in value ? {
        __kind__: "hardBraking",
        hardBraking: value.hardBraking
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    left: null;
} | {
    right: null;
}): Direction {
    return "left" in value ? Direction.left : "right" in value ? Direction.right : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Direction_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: Direction;
}): {
    direction: _Direction;
} {
    return {
        direction: to_candid_Direction_n4(_uploadFile, _downloadFile, value.direction)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "laneDeparture";
    laneDeparture: {
        direction: Direction;
    };
} | {
    __kind__: "speedViolation";
    speedViolation: {
        speed: bigint;
    };
} | {
    __kind__: "hardBraking";
    hardBraking: {
        gForce: number;
    };
}): {
    laneDeparture: {
        direction: _Direction;
    };
} | {
    speedViolation: {
        speed: bigint;
    };
} | {
    hardBraking: {
        gForce: number;
    };
} {
    return value.__kind__ === "laneDeparture" ? {
        laneDeparture: to_candid_record_n3(_uploadFile, _downloadFile, value.laneDeparture)
    } : value.__kind__ === "speedViolation" ? {
        speedViolation: value.speedViolation
    } : value.__kind__ === "hardBraking" ? {
        hardBraking: value.hardBraking
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    left: null;
} | {
    right: null;
} {
    return value == Direction.left ? {
        left: null
    } : value == Direction.right ? {
        right: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
